### ISSUE TITLE
[ERROR] Unable to find starter template for oktadeveloper/jhipster

### ISSUE THREAD

**Issue by shagene** [oktadeveloper/ionic-jhipster-starter#18]
Is it possible to add support for ionic 4?

**Comment by mraible** [comment]
Yes. I hope to do this in the next month. I just figured how how to do OAuth 2.0 support in Ionic 4 yesterday.

https://github.com/mraible/ionic-4-oidc-demo

That’s the main thing I needed to learn how to do for Ionic 4.
