### ISSUE TITLE
Ionic 4 support PR

### ISSUE THREAD

**Issue by fleboulch** [oktadeveloper/ionic-jhipster-starter#19]
@mraible I have a running Ionic 4 with JHipster! [PR for Ionic4 support](https://github.com/fleboulch/ionic-jhipster-starter/pull/1)  
At the moment I have only support for JWT auth.

## Migration plan
Few days ago, we talked a bit about a migration plan. Let me explain my thoughts even if we can't version it.

### Ionic 3 support will be kept

We need to replace
`ionic start ${this.ionicAppName} oktadeveloper/jhipster`
by  
`ionic start ${this.ionicAppName} oktadeveloper/jhipster --type ionic-angular`  
on the generator-jhipster-ionic repo.

The starter path should stay the same on the `ionic-team/starters` project (`ionic-angular/community/oktadeveloper/jhipster`)

### Ionic 4 support added

The starter path need to be different as the base starter from Ionic 4 apps has been rewritten. 
 Now the community starter has to be in `angular/community`.  
I propose, if you are ok with that, to create a new path on the `ionic-team/starters` like `angular/community/XXX/jhipster`.  
And in the generator-jhipster-ionic project we can call it easily with the `ionic start` command

I will do a PR on the generator repo once you have validated my PR on the starter

_Note: I didn't create my PR directly on your project because we should not merge it inside_

**Comment by mraible** [comment]
Great work @fleboulch!

If we have to create a new starter for Ionic 4, I think that solves our versioning problem. The v3 starter can remain at its current location and we can create a new starter with this code for v4.
