### ISSUE TITLE
Entity generation support for V4

### ISSUE THREAD

**Issue by fleboulch** [oktadeveloper/ionic-jhipster-starter#22]

**Comment by fleboulch** [comment]
This issue has to be opened in the generator project

**Comment by fleboulch** [comment]
I started working on it. I've to update both generator and starter. 
I have a sample repo almost ready to support entity for v4. I will share it once it looks good to me. 

I will try to open 2 PRs next week for this feature

**Comment by mraible** [comment]
Hello @fleboulch! I have some time to work on the entity generator this week. Have you had a chance to start working on it?

**Comment by fleboulch** [comment]
Hello @mraible,

I created 2 PRs
On the starter repo, the CI is failing. I didn't have time to check so I will do it tomorrow.
On the generator repo, the PR is in WIP (details on what left todo on the description)
